CREATE TABLE [dbo].[MOVIMIENTOS]
(
[IdMovimiento] [int] NOT NULL IDENTITY(1, 1),
[IdGuid] [uniqueidentifier] NOT NULL CONSTRAINT [DF__MOVIMIENT__IdGui__60A75C0F] DEFAULT (newid()),
[IdUsuario] [int] NOT NULL CONSTRAINT [DF__MOVIMIENT__IdUsu__619B8048] DEFAULT ((1)),
[IdServicio] [tinyint] NOT NULL CONSTRAINT [DF__MOVIMIENT__IdSer__628FA481] DEFAULT ((1)),
[IdEstaActivo] [bit] NOT NULL CONSTRAINT [DF__MOVIMIENT__IdEst__6383C8BA] DEFAULT ((1)),
[IdAdminCreacion] [tinyint] NOT NULL CONSTRAINT [DF__MOVIMIENT__IdAdm__6477ECF3] DEFAULT ((1)),
[FechaCreacion] [datetime] NOT NULL CONSTRAINT [DF__MOVIMIENT__Fecha__656C112C] DEFAULT (getdate()),
[IdAdminActualizacion] [tinyint] NOT NULL CONSTRAINT [DF__MOVIMIENT__IdAdm__66603565] DEFAULT ((1)),
[FechaActualizacion] [datetime] NOT NULL CONSTRAINT [DF__MOVIMIENT__Fecha__6754599E] DEFAULT (getdate())
)
GO
ALTER TABLE [dbo].[MOVIMIENTOS] ADD CONSTRAINT [PK__MOVIMIEN__881A6AE0D17DC4DE] PRIMARY KEY CLUSTERED  ([IdMovimiento])
GO
